baseURL = 'https://my-blog-384.pages.dev/'
languageCode = 'zh-cn'
title = 'NonToriko'  # 这里改成了你的专属名字
theme = "PaperMod"

[params]
    description = "思考记录"
    defaultTheme = "auto" # 自动跟随系统切换深浅色，也可以写死 "dark" 或 "light"
    ShowReadingTime = true # 显示阅读需要几分钟
    ShowWordCount = true # 显示字数

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/"
        weight = 10
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives/"
        weight = 20
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 30
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 40